from typing import Dict, List

import requests
import urllib.parse


def get_plain_dataframe() -> List[Dict]:
    # dataframe also can be generated by pandas csv reader or keqing

    mode_load_method = "network"
    mode_query_type = "amenity=university"  # college, school, research_institute

    OVERPASS_QL_ENDPOINT="https://overpass.ogf.rent-a-planet.com/api/interpreter?data="
    OVERPASS_QL_CONTENT="""
[out:csv(
    ::type,
    ::"id",
    amenity,
    name,
    "name:en",
    "short_name",
    "addr:province",
    operator;
    true; "|"
)];

nwr[{{类型}}]({{边界}});

out meta asc;
"""
    OVERPASS_QL_POLY = """
poly:\"
18.049257 149.051512 
17.970897 148.184966 
17.704213 147.579344 
16.599348 147.153623 
16.612509 147.013547 
15.884737 146.947629 
15.533086 146.557614 
15.776398 145.316159 
15.541025 145.195310 
14.317620 145.360102 
14.104618 145.722651 
13.036675 145.431513 
12.522396 145.634760 
12.071558 146.431269 
12.431218 146.909174 
11.730236 147.904814 
10.493219 148.458246 
9.194298 148.249506 
8.982754 149.468989 
8.559299 149.611811 
9.069557 151.424555 
8.798231 151.721186 
9.486992 152.858275 
9.814624 152.891234 
9.899864 153.231810 
10.082447 153.429564 
9.218695 154.756163 
8.083707 153.893735 
7.844339 154.064023 
7.904192 154.857787 
7.633755 155.040092 
7.609595 155.113563 
7.593260 155.346679 
7.793998 155.360411 
7.928676 155.489501 
8.231879 155.523833 
8.530776 155.990752 
8.799583 156.069030 
8.962403 156.073149 
10.120307 157.489008 
11.636101 159.114985 
12.838587 159.125971 
13.432372 156.137690 
15.146375 155.467524 
16.673036 155.692744 
17.214270 153.539423 
15.987740 152.501215 
16.167202 151.171870 
16.926765 149.852141 
17.143416 149.861754 
17.283777 149.820555 
17.270663 149.740904 
17.372922 149.690093 
17.503939 149.501952 
17.973509 149.262999 
18.049257 149.051512
\"
"""
    OVERPASS_QL_URL = OVERPASS_QL_ENDPOINT+urllib.parse.quote(OVERPASS_QL_CONTENT.replace("{{类型}}", mode_query_type).replace("{{边界}}", OVERPASS_QL_POLY.replace("\n","")))

    query_result = requests.get(
        url=OVERPASS_QL_URL,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
            "Referer": "https://registry.moe.gov.hx/index.html",
        },
    ).content.decode("utf-8")
    # # It is not recommended to read the text directly, but it is recommended to read the network directly and request
    # query_result="""@type|@id|amenity|name|name:en|short_name|addr:province|operator
    # relation|348353|university|国立上京大学|National Shangjing University|NSJU||
    # """

    print(OVERPASS_QL_CONTENT.replace("{{类型}}", mode_query_type).replace("{{边界}}", OVERPASS_QL_POLY.replace("\n","")))

    header = query_result.split("\n")[0].split("|")
    df_raw = query_result.replace(str("|".join(header) + "\n"), "")

    df: List[Dict] = [
        dict(zip(header, item.split("|")))
        for item in list(filter(bool, df_raw.split("\n")))
    ]

    return df
